version: "3"
services:
  dnsmasq:
    restart: always
    image: jpillora/dnsmasq:latest
    ports:
      - 53:53/udp
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro

  traefik:
    restart: always
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic.yml:ro
    depends_on:
      - dnsmasq
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http,https
      - traefik.http.routers.traefik.rule=Host(`traefik.this.test`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.service=api@internal

networks:
  default:
    external:
      name: docker
